# Generated by Django 3.0.5 on 2020-10-22 12:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cosmosapp', '0004_mount'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mount',
            old_name='mount',
            new_name='mounts',
        ),
    ]
