# Generated by Django 3.0.5 on 2020-10-22 12:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cosmosapp', '0007_auto_20201022_1814'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='text',
            new_name='texts',
        ),
    ]
