# Generated by Django 3.0.5 on 2020-10-22 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cosmosapp', '0008_auto_20201022_1817'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='prod',
            name='product_family',
        ),
        migrations.AddField(
            model_name='prod',
            name='product_familys',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
