# Generated by Django 3.0.5 on 2020-10-22 16:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cosmosapp', '0011_blog'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blog',
            old_name='blog',
            new_name='blogs',
        ),
    ]
